// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "get": {
                "description": "Iniciar Sesión del Empleado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Empleado"
                ],
                "summary": "Para el inicio de sesión",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Usuario para iniciar sesión",
                        "name": "usuario",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Clave para iniciar sesión",
                        "name": "clave",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Empleado"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Detalle": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string"
                },
                "estado": {
                    "type": "string"
                },
                "idAuxiliar": {
                    "type": "string"
                },
                "idDetalle": {
                    "type": "integer"
                },
                "idMantenimiento": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "usuarioRegistro": {
                    "type": "string"
                }
            }
        },
        "model.Empleado": {
            "type": "object",
            "properties": {
                "apellidos": {
                    "type": "string"
                },
                "celular": {
                    "type": "string"
                },
                "clave": {
                    "type": "string"
                },
                "detalle": {
                    "$ref": "#/definitions/model.Detalle"
                },
                "direccion": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "estado": {
                    "type": "integer"
                },
                "fechaNacimiento": {
                    "type": "string"
                },
                "huella": {
                    "type": "string"
                },
                "idEmpleado": {
                    "type": "string"
                },
                "idRol": {
                    "type": "integer"
                },
                "nombres": {
                    "type": "string"
                },
                "numeroDocumento": {
                    "type": "string"
                },
                "puesto": {
                    "type": "integer"
                },
                "rol": {
                    "$ref": "#/definitions/model.Rol"
                },
                "sexo": {
                    "type": "integer"
                },
                "sistema": {
                    "type": "boolean"
                },
                "telefono": {
                    "type": "string"
                },
                "tipoDocumento": {
                    "type": "integer"
                },
                "usuario": {
                    "type": "string"
                }
            }
        },
        "model.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Rol": {
            "type": "object",
            "properties": {
                "idRol": {
                    "type": "integer"
                },
                "nombre": {
                    "type": "string"
                },
                "sistema": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
